import { AboutC } from "@/Components/AboutC";
import React from "react";

export const metadata = {
  title: "site| About page",
  description: "Generated by create next app",
};

const About = async () => {
  let data = await fetch("https://api.vercel.app/blog");
  let posts = await data.json();
  return (
    <div>
      <AboutC />
    </div>
  );
};
export default About;
